[package]
name = "mqtt_broker"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitflags = "1.3.2"
lunatic = "0.7.1"
nom = "7.1.0"
num = "0.4.0"
serde = "1.0.132"
mqtt_packet_3_5 = "0.1.0"

[build]
target = "wasm32-wasi"

[target.wasm32-wasi]
runner = "lunatic"